- name: Create a Windows VM
  hosts: localhost
  vars:
    project_name: aap
    vm_name: winders
    vm_iso: install-disk
    vm_storage_class: windows-vms
    vm_running: false
    vm_cpus: 4
    vm_mem: 8Gi
    vm_networks:
      - nic_name: nic1
        network_name: baremetal-network
        network_type: bridge
    vm_labels:
      backup: "true"

  tasks:
    - name: Debug the template
      template:
        src: templates/windowsvm.j2.yml
        dest: "/tmp/template_output.txt"
        
    - name: Create new Windows VM
      kubernetes.core.k8s:
        state: present
        template: templates/windowsvm.j2.yml

    - name: VM info
      kubernetes.core.k8s_info:
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        namespace: "{{ project_name }}"
        label_selectors:
          - "app = {{ vm_name }}"
      register: new_vm
      until: new_vm.resources | length > 0
      retries: 10
    
    - name: print info
      debug:
        var: new_vm
        
    - name: Start Windows VM
      kubernetes.core.k8s:
        state: present
        api_version: kubevirt.io/v1
        kind: VirtualMachine
        name: "{{ vm_name }}"
        namespace: "{{ project_name }}"
        merge_type:
          - strategic-merge
          - merge
        definition:
          spec:
            running: true
