- name: Create a Windows VM
  hosts: localhost
  vars:
    project_name: aap
    vm_name: winders
    vm_iso: install-disk
    vm_storage_class: windows-vms
    vm_running: true
    vm_cpus: 4
    vm_mem: 8Gi
    vm_networks:
      - nic_name: nic1
        network_name: baremetal-network
        network_type: bridge

  tasks:
    - name: Create new Windows VM
      redhat.openshift.k8s:
        state: present
        template: templates/windowsvm.j2.yml
